[build]
  publish = "."
  command = "echo 'Static site, no build needed'"

[build.environment]
  NODE_VERSION = "18"

# API Proxy Configuration
[[redirects]]
  from = "/api/*"
  to = "https://tozyapi-backend.onrender.com/api/:splat"
  status = 200
  force = true

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' https:; connect-src 'self' https://tozyapi-backend.onrender.com https://www.google-analytics.com; frame-ancestors 'none'; base-uri 'self'; object-src 'none';"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=(), usb=(), magnetometer=(), gyroscope=(), accelerometer=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # Performance
    X-DNS-Prefetch-Control = "on"
    X-Permitted-Cross-Domain-Policies = "none"

# Cache Control for Static Assets
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/jpeg"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/png"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/svg+xml"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/webp"

[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/x-icon"

# HTML Pages Cache
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "text/html; charset=utf-8"

# API Responses
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    X-Robots-Tag = "noindex, nofollow"

# Form Processing
[[forms]]
  name = "contact"
  action = "/pages/tesekkurler.html"
  
[[forms]]
  name = "newsletter"

